feature_name: Contact
properties:
  - key: contact_first_letter_field
    description: |
      First Letter Field, the field you sort in when you hit one of the start letters.

      <code>field02</code> - Last name  
      <code>field03</code> - First name
    defaultValue: field02 
    version: 
    reloadable: true
    configcascadeAware: false
    related: 
    file: contact.properties
    packageName: open-xchange-core
    tags: ["Contact"]
  - key: validate_contact_email
    description: |
      Check the entered email address from a new contact for correctness
      (syntactic check user@domain.tld).
    defaultValue: true
    version: 
    reloadable: true
    configcascadeAware: false
    related: 
    file: contact.properties
    packageName: open-xchange-core
    tags: ["Contact"]
  - key: max_image_size
    description: |
      The maximum size in bytes for the upload of contact images. Remember: If you decrease the size after some images where uploaded already, 
      you might trigger errors, for example when trying to modify the contact without adding an image of the correct size.
    defaultValue: 4194304
    version: 
    reloadable: true
    configcascadeAware: false
    related: 
    file: contact.properties
    packageName: open-xchange-core
    tags: ["Contact"]
  - key: com.openexchange.contact.mailAddressAutoSearch
    description: |
      Determines if a search is triggered if the dialog for searching for emailable
      contacts is opened. This dialog is used for selecting recipients for an email
      and for creating distribution lists.
    defaultValue: true
    version: 
    reloadable: true
    configcascadeAware: false
    related: 
    file: contact.properties 
    packageName: open-xchange-core
    tags: ["Contact"]   
  - key: com.openexchange.contact.singleFolderSearch
    description: |
      Searching for contacts can be done in a single folder or globally across all folders. Searching across all folders can cause high server
      and database load because first all visible folders must be determined and if a user has object read permissions in that folders. Software
      internal default is true to prevent high load if the property is not defined. Default here is false because it is easier for the user to
      find contacts.
    defaultValue: false
    version: 
    reloadable: false
    configcascadeAware: false
    related: 
    file: contact.properties
    packageName: open-xchange-core
    tags: ["Contact"] 
  - key: com.openexchange.contacts.characterSearch
    description: |
      Enables/Disables the start letter based quick select of contacts
    defaultValue: true
    version: 
    reloadable: true
    configcascadeAware: false
    related: 
    file: contact.properties
    packageName: open-xchange-core
    tags: ["Contact"] 
  - key: com.openexchange.contacts.allFoldersForAutoComplete
    description: |
      The auto complete search for email addresses may be triggered easily and quite often if a new email is written and a part of a recipients
      address is written. This can lead to high load on the database system if a context has a lot of users and a lot of contacts. Therefore the
      scope if this search can be configured. Set this parameter to <code>true</code> and the auto complete search looks in every readable contact folder for
      contacts with emails addresses matching the already typed letters. If this parameter is configured to <code>false</code>, only three folders are
      considered for the search: the users private default contact folder, his contact folder for collected contacts and the global address book
      if that is enabled for the user.
    defaultValue: true
    version: 
    reloadable: true
    configcascadeAware: false
    related: 
    file: contact.properties
    packageName: open-xchange-core
    tags: ["Contact"]
  - key: com.openexchange.contacts.useCountLookAhead
    description: |
      Contacts in search results may get sorted based on their frequency of usage by the requesting user, so that users experience better suggestions e.g. 
      when auto-completing names of mail recipients while typing. For contacts from external storages that don't have built-in counters for the individual 
      usages, a certain look-ahead factor for the maximum number of results can be specified, which will get applied to the client-defined limit when 
      forwarding the search request to the external storage.  
    defaultValue: 10
    version: 7.10.6
    reloadable: true
    configcascadeAware: true
    related: com.openexchange.MinimumSearchCharacters
    file: contact.properties
    packageName: open-xchange-core
    tags: ["Contact"]
  - key: com.openexchange.contact.scaleVCardImages
    description: |
      Enables/Disables the start letter based quick select of contacts.
    defaultValue: 600x800
    version: 
    reloadable: true
    configcascadeAware: false
    related: 
    file: contact.properties 
    tags: ["Contact"]
  - key: com.openexchange.contact.storeVCards
    description: |
      Specifies whether the original files are persisted during vCard import or 
      CardDAV synchronization. If enabled, the original vCard files will be stored 
      in the appropriate filestore and are considered during export again. If 
      disabled, all not mapped information is discarded and is no longer available
      when exporting the vCard again. 
    defaultValue: true
    version: 
    reloadable: false
    configcascadeAware: false
    related: 
    file: contact.properties
    packageName: open-xchange-core
    tags: ["Contact"]
  - key: com.openexchange.contact.maxVCardSize
    description: |
      Configures the maximum allowed size of a (single) vCard file in bytes. 
      vCards larger than the configured maximum size are rejected and not parsed 
      by the server. A value of <code>0</code> or smaller is considered as unlimited. 
    defaultValue: 4194304
    version: 
    reloadable: true
    configcascadeAware: false
    related: 
    file: contact.properties
    packageName: open-xchange-core
    tags: ["Contact"]
  - key: com.openexchange.contact.image.scaleImages
    description: |
      Enables/Disables the scaling of contact images to a smaller size. 
    defaultValue: true
    version: 
    reloadable: true
    configcascadeAware: false
    related: 
    file: contact.properties
    packageName: open-xchange-core
    tags: ["Contact"]
  - key: com.openexchange.contact.image.maxWidth
    description: |
      Defines the width of scaled contact images.
    defaultValue: 600
    version: 
    reloadable: true
    configcascadeAware: false
    related: 
    file: contact.properties
    packageName: open-xchange-core
    tags: ["Contact"]
  - key: com.openexchange.contact.image.maxHeight
    description: |
      Defines the height of scaled contact images.
    defaultValue: 800
    version: 
    reloadable: true
    configcascadeAware: false
    related: 
    file: contact.properties
    packageName: open-xchange-core
    tags: ["Contact"]
  - key: com.openexchange.contact.image.scaleType
    description: |
      Defines the scale type:
      <ul>
       <li><code>1</code> = contain - maxWidth and maxHeight defines the maximum target dimension</li>
       <li><code>2</code> = cover - maxWidth and maxHeight defines the minimum target dimension</li>
       <li><code>3</code> = auto</li>
      </ul>
    defaultValue: 2
    version: 
    reloadable: true
    configcascadeAware: false
    related: 
    file: contact.properties
    packageName: open-xchange-core
    tags: ["Contact"]
  - key: com.openexchange.contact.fulltextAutocomplete
    description: |
      Configures if a FULLTEXT index dedicated for auto-completion can be used or
      not. Once enabled, an appropriate index is created on the 'prg_contacts' 
      table automatically (covering fields specified through [[com.openexchange.contact.fulltextIndexFields]] property),
      and is used afterwards to serve the "find as you type" 
      auto-completion requests in an efficient way.
      Note that this index requires support for FULLTEXT index types on the used
      InnoDB table, which is available starting with MySQL 5.6.4 (see
      [[http://dev.mysql.com/doc/refman/5.6/en/fulltext-restrictions.html]] for 
      details).
    defaultValue: false
    version: 
    reloadable: false
    configcascadeAware: false
    related: 
    file: contact.properties
    packageName: open-xchange-core
    tags: ["Contact"]
  - key: com.openexchange.contact.fulltextIndexFields
    description: |
      Specifies the contact fields for which a FULLTEXT index is supposed to be created
      provided that property [[com.openexchange.contact.fulltextAutocomplete]] is set to <code>true</code>.
      
      Supported fields:
      <ul>
       <li><code>DISPLAY_NAME</code></li>
       <li><code>SUR_NAME</code></li>
       <li><code>GIVEN_NAME</code></li>
       <li><code>TITLE</code></li>
       <li><code>SUFFIX</code></li>
       <li><code>MIDDLE_NAME</code></li>
       <li><code>COMPANY</code></li>
       <li><code>EMAIL1</code></li>
       <li><code>EMAIL2</code></li>
       <li><code>EMAIL3</code></li>
       <li><code>DEPARTMENT</code></li>
      </ul>

      Note:  
      These fields are only checked one time if [[com.openexchange.contact.fulltextAutocomplete]] is set to <code>true</code>.
      In case the fields are altered later on, manual execution of the associated update task is required to adapt
      the FULLTEXT index to the newly specified fields:
      
      <pre>/opt/open-xchange/sbin/forceupdatetask --task com.openexchange.contact.storage.rdb.groupware.AddFulltextIndexTask &lt;other command-line arguments&gt;</pre>
    defaultValue: DISPLAY_NAME, SUR_NAME, GIVEN_NAME, TITLE, SUFFIX, MIDDLE_NAME, COMPANY, EMAIL1, EMAIL2, EMAIL3 
    version: 
    reloadable: true
    configcascadeAware: false
    related: 
    file: contact.properties
    packageName: open-xchange-core
    tags: ["Contact"]
  - key: com.openexchange.contact.autocomplete.fields
    description: |
      Defines the fields considered within the autocomplete search operation.
      Must be a comma separated list of available fields.
      The available fields are: <code>GIVEN_NAME</code>, <code>SUR_NAME</code>, <code>DISPLAY_NAME</code>, <code>EMAIL1</code>, <code>EMAIL2</code>, <code>EMAIL3</code>, <code>DEPARTMENT</code>
    defaultValue: GIVEN_NAME, SUR_NAME, DISPLAY_NAME, EMAIL1, EMAIL2, EMAIL3
    version: 
    reloadable: true
    configcascadeAware: false
    related: 
    file: contact.properties
    packageName: open-xchange-core
    tags: ["Contact"]
  - key: com.openexchange.contact.showDepartments
    description: |
      Defines whether the departments will be shown as part of the display name. This only affects results that are found under the Global Address Book

      JSLob: io.ox/contacts//showDepartment
    defaultValue: false
    version: 7.10.0
    reloadable: true
    configcascadeAware: false
    related: 
    file: contact.properties
    packageName: open-xchange-core
    tags: ["Contact"]
  - key: com.openexchange.contact.[providerId].enabled
    description: |
      Defines whether the contact provider with the specified identifier is enabled or disabled.
    defaultValue: true
    version: 7.10.5
    reloadable: true
    configcascadeAware: true
    related: 
    file: contact.properties
    packageName: open-xchange-core
    tags: ["Contact"]
  - key: com.openexchange.contactcollector.enabled
    description: |
      Whether enabled or disabled regardless of bundle start-up.
    defaultValue: true
    version: 
    reloadable: false
    configcascadeAware: false
    related: 
    file: contactcollector.properties
    packageName: open-xchange-core
    tags: ["Contact"]
  - key: com.openexchange.contactcollector.searchLimit
    description: |
      Limit the number of contacts that are associated with the same email address
    defaultValue: 5
    version: 
    reloadable: false
    configcascadeAware: false
    related: 
    file: contactcollector.properties
    packageName: open-xchange-core
    tags: ["Contact"]
  - key: com.openexchange.contactcollector.folder.deleteDenied
    description: |
      Whether deletion of contact collector folder will be denied.
    defaultValue: false
    version: 
    reloadable: true
    configcascadeAware: false
    related: 
    file: contactcollector.properties
    packageName: open-xchange-core
    tags: ["Contact"]
  - key: com.openexchange.contactcollector.cleanupUnusedAfter
    description: |
      Specifies the cleanup threshold time span for unused collected contacts. Collected contacts having a last-modified time stamp longer
      in the past than the time span given by this threshold are considered for cleanup.
      
      Accepts units of measurement
      - ms for milliseconds
      - s for seconds
      - m for minutes
      - h for hours
      - D for days
      - W for weeks
      E.g. "4W" for four weeks.

      In addition to the cleanup threshold, a collected contact is only rated as unused if it has only the initial fields set and has a
      use-count value of less than 2.
      
      Cleanup takes place for a certain user whenever the contact collector is triggered for that user; meaning there is no periodic
      back-ground task.
      
      A value of less than or equal to 0 (zero) disables the cleanup.
    defaultValue: 0
    version: 7.10.3
    reloadable: true
    configcascadeAware: true
    related: 
    file: contactcollector.properties
    packageName: open-xchange-core
    tags: ["Contact"]
  - key: com.openexchange.contacts.ldap.accounts
    description: |
      Configures a comma-separated list of LDAP contact providers that are enabled for a user. To enable a specific provider, this provider 
      needs to be defined with its identifier in the file "contact-provider-ldap.yaml". This identifier can then be used to enable it within
      this property.
    defaultValue: 
    version: 7.10.6
    reloadable: true
    configcascadeAware: true
    related: 
    file: ldap-contact-provider.properties
    packageName: open-xchange-contacts-provider-ldap
    tags: ["Contact", "LDAP"]
  - key: com.openexchange.contacts.ldap.cache.expire
    description: |
      Configures the length of time after an ldap contact provider is removed from cache.
      With this setting the cache is refreshed regulary and 
      unused providers are removed from memory as long as they are not needed.

      Accepts units of measurement
      - ms for milliseconds
      - s for seconds
      - m for minutes
      - h for hours
      - D for days
      - W for weeks
      E.g. "1h" for one hour.
    defaultValue: 2h
    version: 7.10.6
    reloadable: true
    configcascadeAware: false
    related: 
    file: ldap-contact-provider.properties
    packageName: open-xchange-contacts-provider-ldap
    tags: ["Contact", "LDAP"]    
  - key: com.openexchange.contacts.usedInPicker.[type]
    description: |
      Defines whether an internal contact folders of a specific type from the default provider will be used as selectable address lists in 
      the enterprise contact picker or not. 
      [type] must be replaced by the folder type ('private', 'shared', 'public' or 'system').
    defaultValue: true
    version: 7.10.6
    reloadable: true
    configcascadeAware: true
    related: ["com.openexchange.contacts.usedInPicker.[type].protected"]
    file: contact.properties
    packageName: open-xchange-core
    tags: ["Contact"]
  - key: com.openexchange.contacts.usedInPicker.[type].protected
    description: |
      Configures whether the default 'usedInPicker' setting for a certain folder type can be overwritten by clients or not.  
      [type] must be replaced by the folder type ('private', 'shared', 'public' or 'system').
    defaultValue: true
    version: 7.10.6
    reloadable: true
    configcascadeAware: true
    related: ["com.openexchange.contacts.usedInPicker.[type]"]
    file: contact.properties
    packageName: open-xchange-core
    tags: ["Contact"]
  - key: com.openexchange.contacts.gabFolderName
    description: |
      Defines the Global Address Book folder name.
      Possible values:
      <ul>
        <li><code>global_address_book</code> 'Global address book'</li>
        <li><code>internal_users</code> 'Internal Users'</li>
        <li><code>all_users</code> 'All Users'</li> 
        <li><code>custom</code> Custom (see <code>com.openexchange.contacts.customGabFolderName.[locale]</code>)</li>
      </ul>
      The property can be specified through the config-cascade down to scope 'context'.
    defaultValue: all_users
    version: 7.10.6
    reloadable: false
    configcascadeAware: true
    related: ["com.openexchange.contacts.customGabFolderName.[locale]"]
    file: contact.properties
    packageName: open-xchange-core
    tags: ["Contact", "Global Address Book"]
  - key: com.openexchange.contacts.customGabFolderName.[locale]
    description: |
      Defines a custom Global Address Book folder name.
      [locale] can be replaced to define a locale specific custom name. A fallback can be specified by omitting [locale]
      The properties are only considered if [[com.openexchange.contacts.gabFolderName]] is set to <code>custom</code>.
      Example:
      <pre>
      com.openexchange.contacts.customGabFolderName=Family Members
      com.openexchange.contacts.customGabFolderName.de_DE=Familienmitglieder
      </pre>
      The property can be specified through the config-cascade down to scope 'context'.
      It is also recommended to add custom folder names to the reserved folder names file in `/opt/open-xchange/etc/folder-reserved-names` to prevent unintended side effects.
    defaultValue:
    version: 7.10.6
    reloadable: false
    configcascadeAware: true
    related: ["com.openexchange.contacts.gabFolderName"]
    file: contact.properties
    packageName: open-xchange-core
    tags: ["Contact", "Global Address Book"]
