/*
 * @copyright Copyright (c) OX Software GmbH, Germany <info@open-xchange.com>
 * @license AGPL-3.0
 *
 * This code is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with OX App Suite.  If not, see <https://www.gnu.org/licenses/agpl-3.0.txt>.
 *
 * Any use of the work other than as authorized under this license or copyright law is prohibited.
 *
 */

package org.glassfish.grizzly.http.server;


/**
 * {@link RequestFormPostSizeExceededException} - Thrown if maximum size allowed for a POST body generated by an HTML form has been exceeded.
 *
 * @author <a href="mailto:thorben.betten@open-xchange.com">Thorben Betten</a>
 * @since v8.0.0
 */
public class RequestFormPostSizeExceededException extends RuntimeException {

    private static final long serialVersionUID = 1713053851058131394L;

    /**
     * Initializes a new {@link RequestFormPostSizeExceededException}.
     */
    public RequestFormPostSizeExceededException() {
        this("Max. size allowed for a POST body generated by an HTML form has been exceeded");
    }

    /**
     * Initializes a new {@link RequestFormPostSizeExceededException}.
     *
     * @param message The detail message. The detail message is saved for later retrieval by the {@link #getMessage()} method.
     */
    public RequestFormPostSizeExceededException(String message) {
        super(message);
    }

    /**
     * Initializes a new {@link RequestFormPostSizeExceededException}.
     *
     * @param cause The cause (which is saved for later retrieval by the
     *         {@link #getCause()} method).  (A {@code null} value is
     *         permitted, and indicates that the cause is nonexistent or
     *         unknown.)
     */
    public RequestFormPostSizeExceededException(Throwable cause) {
        super(cause);
    }

    /**
     * Initializes a new {@link RequestFormPostSizeExceededException}.
     *
     * @param message The detail message. The detail message is saved for later retrieval by the {@link #getMessage()} method.
     * @param cause The cause (which is saved for later retrieval by the
     *         {@link #getCause()} method).  (A {@code null} value is
     *         permitted, and indicates that the cause is nonexistent or
     *         unknown.)
     */
    public RequestFormPostSizeExceededException(String message, Throwable cause) {
        super(message, cause);
    }

}
