{{- if .Values.enableInitialization -}}
{{- $oxguardpass := printf "MC%s\nRC%s" (randBytes 20) (randBytes 20) }}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace (printf "%s-%s" (include "ox-common.names.fullname" . ) "guard-secret")) }}
{{- if $secret }}
{{- $oxguardpass = index $secret.data.oxguardpass | b64dec }}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ox-common.names.fullname" . }}-guard-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ox-common.labels.standard" . | nindent 4 }}
data:
  oxguardpass: |-
    {{ $oxguardpass | b64enc }}
{{- end -}}
