apiVersion: v1
kind: Pod
metadata:
  name: middleware-core-blackduck
spec:
  securityContext:
      runAsNonRoot: true
      runAsUser: 1000
  containers:
  - name: jnlp
    env:
    - name: JAVA_OPTS
      value: "-XX:MaxRAMPercentage=50"
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        memory: 1Gi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - all
    volumeMounts:
    - mountPath: /shared-data
      name: shared-data
  - name: blackduck
    image: registry.gitlab.open-xchange.com/jenkins/runner-blackduck:latest
    imagePullPolicy: Always
    command:
    - sleep
    args:
    - 99d
    resources:
      limits:
        memory: 5Gi
      requests:
        memory: 5Gi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - all
    volumeMounts:
    - mountPath: /shared-data
      name: shared-data
  - name: ant
    image: frekele/ant:1.9.11-jdk8
    command:
    - sleep
    args:
    - 99d
    resources:
      limits:
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 256Mi
    securityContext:
      readOnlyRootFilesystem: true
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - all
  imagePullSecrets:
  - name: gitlab
  volumes:
  - name: shared-data
    persistentVolumeClaim:
      claimName: middleware-core-pvc