apiVersion: v1
kind: Pod
metadata:
  name: middleware-core-gradle
spec:
  securityContext:
      runAsNonRoot: true
      runAsUser: 1000
  containers:
  - name: jnlp
    env:
      - name: JAVA_OPTS
        value: "-XX:MaxRAMPercentage=50"
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        memory: 1Gi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - all
    volumeMounts:
      - mountPath: /shared-data
        name: shared-data
  volumes:
    - name: shared-data
      persistentVolumeClaim:
        claimName: middleware-core-pvc