package com.openexchange.sessiond.soap.soap;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;

/**
 * This class was generated by Apache CXF 2.6.0
 * 2012-06-01T18:24:59.078+02:00
 * Generated source version: 2.6.0
 *
 */
@WebService(targetNamespace = "http://soap.sessiond.openexchange.com", name = "OXSessionServicePortType")
@XmlSeeAlso({com.openexchange.sessiond.soap.io.ObjectFactory.class, ObjectFactory.class, com.openexchange.sessiond.soap.rmi.ObjectFactory.class, com.openexchange.sessiond.soap.exceptions.ObjectFactory.class, com.openexchange.sessiond.soap.dataobjects.ObjectFactory.class})
public interface OXSessionServicePortType {

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @Action(input = "urn:clearUserSession", output = "urn:clearUserSessionResponse", fault = {@FaultAction(className = InvalidCredentialsException_Exception.class, value = "urn:clearUserSessionInvalidCredentialsException"), @FaultAction(className = RemoteException_Exception.class, value = "urn:clearUserSessionRemoteException"), @FaultAction(className = NoSuchUserException_Exception.class, value = "urn:clearUserSessionNoSuchUserException")})
    @WebMethod(action = "urn:clearUserSession")
    public void clearUserSession(
        @WebParam(partName = "parameters", name = "clearUserSession", targetNamespace = "http://soap.sessiond.openexchange.com")
        ClearUserSession parameters
    ) throws InvalidCredentialsException_Exception, RemoteException_Exception, NoSuchUserException_Exception;

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @Action(input = "urn:clearUserSessions", output = "urn:clearUserSessionsResponse", fault = {@FaultAction(className = InvalidCredentialsException_Exception.class, value = "urn:clearUserSessionsInvalidCredentialsException"), @FaultAction(className = RemoteException_Exception.class, value = "urn:clearUserSessionsRemoteException"), @FaultAction(className = NoSuchUserException_Exception.class, value = "urn:clearUserSessionsNoSuchUserException")})
    @WebMethod(action = "urn:clearUserSessions")
    public void clearUserSessions(
        @WebParam(partName = "parameters", name = "clearUserSessions", targetNamespace = "http://soap.sessiond.openexchange.com")
        ClearUserSessions parameters
    ) throws InvalidCredentialsException_Exception, RemoteException_Exception, NoSuchUserException_Exception;

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @Action(input = "urn:clearContextSessions", output = "urn:clearContextSessionsResponse", fault = {@FaultAction(className = InvalidCredentialsException_Exception.class, value = "urn:clearContextSessionsInvalidCredentialsException"), @FaultAction(className = RemoteException_Exception.class, value = "urn:clearContextSessionsRemoteException"), @FaultAction(className = NoSuchContextException_Exception.class, value = "urn:clearContextSessionsNoSuchContextException")})
    @WebMethod(action = "urn:clearContextSessions")
    public void clearContextSessions(
        @WebParam(partName = "parameters", name = "clearContextSessions", targetNamespace = "http://soap.sessiond.openexchange.com")
        ClearContextSessions parameters
    ) throws InvalidCredentialsException_Exception, RemoteException_Exception, NoSuchContextException_Exception;

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @Action(input = "urn:clearContextsSessions", output = "urn:clearContextsSessionsResponse", fault = {@FaultAction(className = InvalidCredentialsException_Exception.class, value = "urn:clearContextsSessionsInvalidCredentialsException"), @FaultAction(className = RemoteException_Exception.class, value = "urn:clearContextsSessionsRemoteException"), @FaultAction(className = NoSuchContextException_Exception.class, value = "urn:clearContextsSessionsNoSuchContextException")})
    @WebMethod(action = "urn:clearContextsSessions")
    public void clearContextsSessions(
        @WebParam(partName = "parameters", name = "clearContextsSessions", targetNamespace = "http://soap.sessiond.openexchange.com")
        ClearContextsSessions parameters
    ) throws InvalidCredentialsException_Exception, RemoteException_Exception, NoSuchContextException_Exception;

}
