
package com.openexchange.sessiond.soap.soap;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.0
 * 2012-06-01T18:24:58.891+02:00
 * Generated source version: 2.6.0
 */

@WebFault(name = "RemoteException", targetNamespace = "http://soap.sessiond.openexchange.com")
public class RemoteException_Exception extends java.lang.Exception {

    private com.openexchange.sessiond.soap.soap.RemoteException remoteException;

    public RemoteException_Exception() {
        super();
    }

    public RemoteException_Exception(String message) {
        super(message);
    }

    public RemoteException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public RemoteException_Exception(String message, com.openexchange.sessiond.soap.soap.RemoteException remoteException) {
        super(message);
        this.remoteException = remoteException;
    }

    public RemoteException_Exception(String message, com.openexchange.sessiond.soap.soap.RemoteException remoteException, Throwable cause) {
        super(message, cause);
        this.remoteException = remoteException;
    }

    public com.openexchange.sessiond.soap.soap.RemoteException getFaultInfo() {
        return this.remoteException;
    }
}
