package com.openexchange.admin.soap.secondaryaccount.soap;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.0
 * 2012-06-01T18:46:00.795+02:00
 * Generated source version: 2.6.0
 *
 */
@WebServiceClient(name = "OXSecondaryAccountService",
                  // wsdlLocation = "null",
                  targetNamespace = "http://soap.admin.openexchange.com")
public class OXSecondaryAccountService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://soap.admin.openexchange.com", "OXSecondaryAccountService");
    public final static QName OXSecondaryAccountServiceHttpSoap12Endpoint = new QName("http://soap.admin.openexchange.com", "OXSecondaryAccountServiceHttpSoap12Endpoint");
    public final static QName OXSecondaryAccountServiceHttpsEndpoint = new QName("http://soap.admin.openexchange.com", "OXSecondaryAccountServiceHttpsEndpoint");
    public final static QName OXSecondaryAccountServiceHttpsSoap11Endpoint = new QName("http://soap.admin.openexchange.com", "OXSecondaryAccountServiceHttpsSoap11Endpoint");
    public final static QName OXSecondaryAccountServiceHttpsSoap12Endpoint = new QName("http://soap.admin.openexchange.com", "OXSecondaryAccountServiceHttpsSoap12Endpoint");
    public final static QName OXSecondaryAccountServiceHttpEndpoint = new QName("http://soap.admin.openexchange.com", "OXSecondaryAccountServiceHttpEndpoint");
    public final static QName OXSecondaryAccountServiceHttpSoap11Endpoint = new QName("http://soap.admin.openexchange.com", "OXSecondaryAccountServiceHttpSoap11Endpoint");
    static {
        WSDL_LOCATION = null;
    }

    public OXSecondaryAccountService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public OXSecondaryAccountService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OXSecondaryAccountService() {
        super(WSDL_LOCATION, SERVICE);
    }


    /**
     *
     * @return
     *     returns OXSecondaryAccountServicePortType
     */
    @WebEndpoint(name = "OXSecondaryAccountServiceHttpSoap12Endpoint")
    public OXSecondaryAccountServicePortType getOXSecondaryAccountServiceHttpSoap12Endpoint() {
        return super.getPort(OXSecondaryAccountServiceHttpSoap12Endpoint, OXSecondaryAccountServicePortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OXSecondaryAccountServicePortType
     */
    @WebEndpoint(name = "OXSecondaryAccountServiceHttpSoap12Endpoint")
    public OXSecondaryAccountServicePortType getOXSecondaryAccountServiceHttpSoap12Endpoint(WebServiceFeature... features) {
        return super.getPort(OXSecondaryAccountServiceHttpSoap12Endpoint, OXSecondaryAccountServicePortType.class, features);
    }
    /**
     *
     * @return
     *     returns OXSecondaryAccountServicePortType
     */
    @WebEndpoint(name = "OXSecondaryAccountServiceHttpsEndpoint")
    public OXSecondaryAccountServicePortType getOXSecondaryAccountServiceHttpsEndpoint() {
        return super.getPort(OXSecondaryAccountServiceHttpsEndpoint, OXSecondaryAccountServicePortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OXSecondaryAccountServicePortType
     */
    @WebEndpoint(name = "OXSecondaryAccountServiceHttpsEndpoint")
    public OXSecondaryAccountServicePortType getOXSecondaryAccountServiceHttpsEndpoint(WebServiceFeature... features) {
        return super.getPort(OXSecondaryAccountServiceHttpsEndpoint, OXSecondaryAccountServicePortType.class, features);
    }
    /**
     *
     * @return
     *     returns OXSecondaryAccountServicePortType
     */
    @WebEndpoint(name = "OXSecondaryAccountServiceHttpsSoap11Endpoint")
    public OXSecondaryAccountServicePortType getOXSecondaryAccountServiceHttpsSoap11Endpoint() {
        return super.getPort(OXSecondaryAccountServiceHttpsSoap11Endpoint, OXSecondaryAccountServicePortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OXSecondaryAccountServicePortType
     */
    @WebEndpoint(name = "OXSecondaryAccountServiceHttpsSoap11Endpoint")
    public OXSecondaryAccountServicePortType getOXSecondaryAccountServiceHttpsSoap11Endpoint(WebServiceFeature... features) {
        return super.getPort(OXSecondaryAccountServiceHttpsSoap11Endpoint, OXSecondaryAccountServicePortType.class, features);
    }
    /**
     *
     * @return
     *     returns OXSecondaryAccountServicePortType
     */
    @WebEndpoint(name = "OXSecondaryAccountServiceHttpsSoap12Endpoint")
    public OXSecondaryAccountServicePortType getOXSecondaryAccountServiceHttpsSoap12Endpoint() {
        return super.getPort(OXSecondaryAccountServiceHttpsSoap12Endpoint, OXSecondaryAccountServicePortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OXSecondaryAccountServicePortType
     */
    @WebEndpoint(name = "OXSecondaryAccountServiceHttpsSoap12Endpoint")
    public OXSecondaryAccountServicePortType getOXSecondaryAccountServiceHttpsSoap12Endpoint(WebServiceFeature... features) {
        return super.getPort(OXSecondaryAccountServiceHttpsSoap12Endpoint, OXSecondaryAccountServicePortType.class, features);
    }
    /**
     *
     * @return
     *     returns OXSecondaryAccountServicePortType
     */
    @WebEndpoint(name = "OXSecondaryAccountServiceHttpEndpoint")
    public OXSecondaryAccountServicePortType getOXSecondaryAccountServiceHttpEndpoint() {
        return super.getPort(OXSecondaryAccountServiceHttpEndpoint, OXSecondaryAccountServicePortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OXSecondaryAccountServicePortType
     */
    @WebEndpoint(name = "OXSecondaryAccountServiceHttpEndpoint")
    public OXSecondaryAccountServicePortType getOXSecondaryAccountServiceHttpEndpoint(WebServiceFeature... features) {
        return super.getPort(OXSecondaryAccountServiceHttpEndpoint, OXSecondaryAccountServicePortType.class, features);
    }
    /**
     *
     * @return
     *     returns OXSecondaryAccountServicePortType
     */
    @WebEndpoint(name = "OXSecondaryAccountServiceHttpSoap11Endpoint")
    public OXSecondaryAccountServicePortType getOXSecondaryAccountServiceHttpSoap11Endpoint() {
        return super.getPort(OXSecondaryAccountServiceHttpSoap11Endpoint, OXSecondaryAccountServicePortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OXSecondaryAccountServicePortType
     */
    @WebEndpoint(name = "OXSecondaryAccountServiceHttpSoap11Endpoint")
    public OXSecondaryAccountServicePortType getOXSecondaryAccountServiceHttpSoap11Endpoint(WebServiceFeature... features) {
        return super.getPort(OXSecondaryAccountServiceHttpSoap11Endpoint, OXSecondaryAccountServicePortType.class, features);
    }

}
