{
 "title": "App Suite / Core-Middleware",
 "tags": [
  "java",
  "app-suite"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1m,5m,1h,6h,1d" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_pod_info, namespace)"
   },
   {
    "name": "app",
    "label": "App",
    "query": "label_values(up{namespace=\"$namespace\"}, app)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(kube_pod_info{namespace=\"$namespace\", pod=~\".*$app.*\"}, pod)"
   },
   {
    "name": "dbpool",
    "label": "DB Pool",
    "query": "label_values(appsuite_mysql_connections_total,pool)"
   },
   {
    "name": "davinterface",
    "label": "DAV Interface",
    "query": "label_values(appsuite_webdav_requests_seconds_count,interface)"
   },
   {
    "name": "httpclient",
    "label": "HTTP Client",
    "query": "label_values(appsuite_httpclient_requests_seconds_count,client)"
   },
   {
    "name": "circuitbreaker_name",
    "label": "CircuitBreaker Name",
    "query": "label_values(appsuite_circuitbreaker_state, name)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Server Version",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "appsuite_version_info{pod=\"$pod\"}",
     "legendFormat": "{{server_version}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_uptime_seconds{pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Health Status",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "appsuite_health_status{pod=\"$pod\"} > 0"
    }
   ]
  },
  { "title": "Sessions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Total",
   "type": "singlestat",
   "description": "The number of total sessions.",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "appsuite_sessions_total{client=\"all\", pod=\"$pod\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Active",
   "type": "singlestat",
   "description": "The number of active sessions or in other words the number of sessions within the first two short term containers.",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "appsuite_sessions_active_total{client=\"all\", pod=\"$pod\"}",
     "legendFormat": "Active"
    }
   ]
  },
  {
   "title": "Short Term",
   "type": "singlestat",
   "description": "The number of sessions in the short term containers.",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "appsuite_sessions_short_term_total{client=\"all\", pod=\"$pod\"}",
     "legendFormat": "Short Term"
    }
   ]
  },
  {
   "title": "Long Term",
   "type": "singlestat",
   "description": "The number of sessions in the long term containers.",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "appsuite_sessions_long_term_total{client=\"all\", pod=\"$pod\"}",
     "legendFormat": "Long Term"
    }
   ]
  },
  {
   "title": "Overview",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 6 },
   "yaxes": [
    { "format": "short", "label": "Sessions" }
   ],
   "targets": [
    {
     "expr": "appsuite_sessions_total{client=\"all\", pod=\"$pod\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "appsuite_sessions_active_total{client=\"all\", pod=\"$pod\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "appsuite_sessions_short_term_total{client=\"all\", pod=\"$pod\"}",
     "legendFormat": "Short Term"
    },
    {
     "expr": "appsuite_sessions_long_term_total{client=\"all\", pod=\"$pod\"}",
     "legendFormat": "Long Term"
    },
    {
     "expr": "appsuite_sessions_max{client=\"all\", pod=\"$pod\"}",
     "legendFormat": "Max"
    }
   ]
  },
  { "title": "SessionStorage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Consumed memory",
   "type": "graph",
   "description": "Consumed memory of stored sessions held by this node in.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "appsuite_sessionstorage_memory_bytes{pod=\"$pod\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Stored sessions",
   "type": "graph",
   "description": "Number of stored sessions held by this node.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "appsuite_sessionstorage_sessions_total{pod=\"$pod\"}",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "sum(appsuite_sessionstorage_sessions_total{type=\"owned\"})",
     "legendFormat": "global"
    }
   ]
  },
  { "title": "ThreadPool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "ThreadPool",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "Threads" }
   ],
   "targets": [
    {
     "expr": "appsuite_executor_active_threads{name=\"main\",pod=\"$pod\"}",
     "legendFormat": "ActiveCount"
    },
    {
     "expr": "appsuite_executor_pool_size_threads{name=\"main\",pod=\"$pod\"}",
     "legendFormat": "PoolSize"
    }
   ]
  },
  {
   "title": "ThreadPool Tasks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "Tasks/s" }
   ],
   "targets": [
    {
     "expr": "appsuite_executor_queue_remaining_tasks{name=\"main\",pod=\"$pod\"}",
     "legendFormat": "Remaining"
    },
    {
     "expr": "appsuite_executor_queued_tasks{name=\"main\",pod=\"$pod\"}",
     "legendFormat": "Queued"
    },
    {
     "expr": "rate(appsuite_executor_completed_tasks_total{name=\"main\",pod=\"$pod\"}[$interval])",
     "legendFormat": "Completed"
    }
   ]
  },
  { "title": "Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Hit Ratio",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 33 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(appsuite_jcs_cache_hits_total{pod=\"$pod\"}[$interval])) / (sum(rate(appsuite_jcs_cache_hits_total{pod=\"$pod\"}[$interval])) + sum(rate(appsuite_jcs_cache_misses_total{pod=\"$pod\"}[$interval])))"
    }
   ]
  },
  {
   "title": "Miss Ratio",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 33 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(appsuite_jcs_cache_misses_total{pod=\"$pod\"}[$interval])) / (sum(rate(appsuite_jcs_cache_hits_total{pod=\"$pod\"}[$interval])) + sum(rate(appsuite_jcs_cache_misses_total{pod=\"$pod\"}[$interval])))"
    }
   ]
  },
  {
   "title": "Cache Hit/Miss Ratio",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 3, "y": 33 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(appsuite_jcs_cache_hits_total{pod=\"$pod\"}[$interval])) / (sum(rate(appsuite_jcs_cache_hits_total{pod=\"$pod\"}[$interval])) + sum(rate(appsuite_jcs_cache_misses_total{pod=\"$pod\"}[$interval])))",
     "legendFormat": "Hit Ratio"
    },
    {
     "expr": "sum(rate(appsuite_jcs_cache_misses_total{pod=\"$pod\"}[$interval])) / (sum(rate(appsuite_jcs_cache_hits_total{pod=\"$pod\"}[$interval])) + sum(rate(appsuite_jcs_cache_misses_total{pod=\"$pod\"}[$interval])))",
     "legendFormat": "Miss Ratio"
    }
   ]
  },
  {
   "title": "Cache Operations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(appsuite_jcs_cache_puts_total{pod=\"$pod\"}[$interval]))",
     "legendFormat": "Puts"
    },
    {
     "expr": "sum(rate(appsuite_jcs_cache_removals_total{pod=\"$pod\"}[$interval]))",
     "legendFormat": "Removals"
    }
   ]
  },
  {
   "title": "Top 5 Cache Regions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5,avg_over_time(appsuite_jcs_cache_elements_total{pod=\"$pod\"}[${__range_s}s]))",
     "legendFormat": "{{region}}"
    }
   ]
  },
  { "title": "DB Pool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Timeout Error Ratio",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 50 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum without (instance, type, class, pool, service) (rate(appsuite_mysql_connections_timeout_total{pod=\"$app\"}[1m])) / sum without (instance, type, class, pool, service) (rate(appsuite_mysql_connections_total{pod=\"$app\"}[1m]))"
    }
   ]
  },
  {
   "title": "Active ConfigDB",
   "type": "singlestat",
   "description": "**Active ConfigDB Connections**",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 50 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(appsuite_mysql_connections_active{class=~\"configdb\"})"
    }
   ]
  },
  {
   "title": "Active UserDB",
   "type": "singlestat",
   "description": "**Active UserDB Connections**",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 54 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(appsuite_mysql_connections_active{class=~\"userdb\"})"
    }
   ]
  },
  {
   "title": "DB Pools",
   "type": "table",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 50 },
   "targets": [
    {
     "expr": "count(appsuite_mysql_connections_total{pool=~\".*[0-9]+\"}) by (pool, class, type)"
    }
   ]
  },
  {
   "title": "ConfigDB Read Connections",
   "type": "graph",
   "description": "The total number of pooled and active connections of this db pool.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "appsuite_mysql_connections_total{class=\"configdb\",pod=\"$pod\",type=\"read\"}",
     "legendFormat": "Pooled"
    },
    {
     "expr": "appsuite_mysql_connections_active{class=\"configdb\",pod=\"$pod\",type=\"read\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "appsuite_mysql_connections_idle{class=\"configdb\",pod=\"$pod\",type=\"read\"}",
     "legendFormat": "Idle"
    },
    {
     "expr": "sum(appsuite_mysql_connections_max{class=\"configdb\",pod=\"$pod\",type=\"read\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "ConfigDB Write Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "appsuite_mysql_connections_total{class=\"configdb\",pod=\"$pod\",type=\"write\"}",
     "legendFormat": "Pooled"
    },
    {
     "expr": "appsuite_mysql_connections_active{class=\"configdb\",pod=\"$pod\",type=\"write\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "appsuite_mysql_connections_idle{class=\"configdb\",pod=\"$pod\",type=\"write\"}",
     "legendFormat": "Idle"
    },
    {
     "expr": "sum(appsuite_mysql_connections_max{class=\"configdb\",pod=\"$pod\",type=\"write\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "UserDB $dbpool Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "appsuite_mysql_connections_total{class=~\"userdb\",pod=\"$pod\",pool=~\"$dbpool\"}",
     "legendFormat": "Pooled (Type: {{type}}, Pool: {{pool}})"
    },
    {
     "expr": "appsuite_mysql_connections_active{class=~\"userdb\",pod=\"$pod\",pool=~\"$dbpool\"}",
     "legendFormat": "Active (Type: {{type}}, Pool: {{pool}})"
    },
    {
     "expr": "appsuite_mysql_connections_idle{class=~\"userdb\",pod=\"$pod\",pool=~\"$dbpool\"}",
     "legendFormat": "Idle (Type: {{type}}, Pool: {{pool}})"
    },
    {
     "expr": "appsuite_mysql_connections_max{class=~\"userdb\",pod=\"$pod\",pool=~\"$dbpool\"}",
     "legendFormat": "Max (Type: {{type}}, Pool: {{pool}})"
    }
   ]
  },
  {
   "title": "HTTP Client \"$httpclient\"",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 }
  },
  {
   "title": "Requests (per-second)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "cps", "label": "Counts/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(appsuite_httpclient_requests_seconds_count{pod=\"$pod\",client=\"$httpclient\"}[$interval])) by (client,instance)",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(rate(appsuite_httpclient_requests_seconds_count{pod=\"$pod\",client=\"$httpclient\",status!~\"[45][0-9]{2}\"}[$interval])) by (client,instance)",
     "legendFormat": "OK"
    },
    {
     "expr": "sum(rate(appsuite_httpclient_requests_seconds_count{pod=\"$pod\",client=\"$httpclient\",status=~\"[45][0-9]{2}\"}[$interval])) by (client,instance)",
     "legendFormat": "KO"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "appsuite_httpclient_connections_pending{pod=\"$pod\",client=~\"$httpclient\"}",
     "legendFormat": "Pending"
    },
    {
     "expr": "appsuite_httpclient_connections_available{pod=\"$pod\",client=~\"$httpclient\"}",
     "legendFormat": "Available"
    },
    {
     "expr": "appsuite_httpclient_connections_leased{pod=\"$pod\",client=~\"$httpclient\"}",
     "legendFormat": "Leased"
    },
    {
     "expr": "appsuite_httpclient_connections_max{pod=\"$pod\",client=~\"$httpclient\"}",
     "legendFormat": "Max"
    }
   ]
  },
  { "title": "HTTP API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 } },
  {
   "title": "Requests (per-second)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
   "yaxes": [
    { "format": "cps", "label": "Counts/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(appsuite_httpapi_requests_seconds_count{pod=\"$pod\"}[$interval]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(rate(appsuite_httpapi_requests_seconds_count{status=~\"OK\",pod=\"$pod\"}[$interval]))",
     "legendFormat": "OK"
    },
    {
     "expr": "sum(rate(appsuite_httpapi_requests_seconds_count{status!~\"OK\",pod=\"$pod\"}[$interval]))",
     "legendFormat": "KO"
    }
   ]
  },
  {
   "title": "Response Time Percentiles",
   "type": "graph",
   "description": "HTTP API response time percentiles.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
   "yaxes": [
    { "format": "s", "label": "Response Time" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(appsuite_httpapi_requests_seconds_bucket{pod=\"$pod\"}[$interval])) by (le,instance))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(appsuite_httpapi_requests_seconds_bucket{pod=\"$pod\"}[$interval])) by (le,instance))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(appsuite_httpapi_requests_seconds_bucket{pod=\"$pod\"}[$interval])) by (le,instance))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(appsuite_httpapi_requests_seconds_bucket{pod=\"$pod\"}[$interval])) by (le,instance))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(appsuite_httpapi_requests_seconds_bucket{pod=\"$pod\"}[$interval])) by (le,instance))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(appsuite_httpapi_requests_seconds_bucket{pod=\"$pod\"}[$interval])) by (le,instance))",
     "legendFormat": "p999"
    },
    {
     "expr": "sum(rate(appsuite_httpapi_requests_seconds_sum{pod=\"$pod\"}[$interval]))/sum(rate(appsuite_httpapi_requests_seconds_count{pod=\"$pod\"}[$interval]))",
     "legendFormat": "avg"
    },
    {
     "expr": "sum(appsuite_httpapi_requests_seconds_max{pod=\"$pod\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Top 5 Requests (99th percentile)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 92 },
   "yaxes": [
    { "format": "s", "label": "Response Time" }
   ],
   "targets": [
    {
     "expr": "topk(5,histogram_quantile(0.99, sum(rate(appsuite_httpapi_requests_seconds_bucket{pod=\"$pod\"}[${__range_s}s])) by (le, module, action, instance)))",
     "legendFormat": "{{module}}/{{action}}"
    }
   ]
  },
  { "title": "REST API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 100 } },
  {
   "title": "Requests (per-second)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 101 },
   "yaxes": [
    { "format": "cps", "label": "Counts/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(appsuite_restapi_requests_seconds_count{pod=\"$pod\"}[$interval]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(rate(appsuite_restapi_requests_seconds_count{status!~\"[45][0-9]{2}\",pod=\"$pod\"}[$interval]))",
     "legendFormat": "OK"
    },
    {
     "expr": "sum(rate(appsuite_restapi_requests_seconds_count{status=~\"[45][0-9]{2}\",pod=\"$pod\"}[$interval]))",
     "legendFormat": "KO"
    }
   ]
  },
  {
   "title": "Response Time Percentiles",
   "type": "graph",
   "description": "REST API response time percentiles.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 101 },
   "yaxes": [
    { "format": "s", "label": "Response Time" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(appsuite_restapi_requests_seconds_bucket{pod=\"$pod\"}[$interval])) by (le,instance))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(appsuite_restapi_requests_seconds_bucket{pod=\"$pod\"}[$interval])) by (le,instance))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(appsuite_restapi_requests_seconds_bucket{pod=\"$pod\"}[$interval])) by (le,instance))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(appsuite_restapi_requests_seconds_bucket{pod=\"$pod\"}[$interval])) by (le,instance))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(appsuite_restapi_requests_seconds_bucket{pod=\"$pod\"}[$interval])) by (le,instance))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(appsuite_restapi_requests_seconds_bucket{pod=\"$pod\"}[$interval])) by (le,instance))",
     "legendFormat": "p999"
    },
    {
     "expr": "sum(rate(appsuite_restapi_requests_seconds_sum{pod=\"$pod\"}[$interval]))/sum(rate(appsuite_restapi_requests_seconds_count{pod=\"$pod\"}[$interval]))",
     "legendFormat": "avg"
    },
    {
     "expr": "sum(appsuite_restapi_requests_seconds_max{pod=\"$pod\"})",
     "legendFormat": "max"
    }
   ]
  },
  { "title": "WebDAV API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 109 } },
  {
   "title": "Requests (per-second)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 110 },
   "yaxes": [
    { "format": "cps", "label": "Counts/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(appsuite_webdav_requests_seconds_count{pod=\"$pod\"}[$interval]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(rate(appsuite_webdav_requests_seconds_count{status=~\"OK|^0\",pod=\"$pod\"}[$interval]))",
     "legendFormat": "OK"
    },
    {
     "expr": "sum(rate(appsuite_webdav_requests_seconds_count{status!~\"OK|^0\",pod=\"$pod\"}[$interval]))",
     "legendFormat": "KO"
    }
   ]
  },
  {
   "title": "Response Time Percentiles $davinterface",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 118 },
   "repeat": "davinterface",
   "yaxes": [
    { "format": "s", "label": "Response Time" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(appsuite_webdav_requests_seconds_bucket{pod=\"$pod\",interface=\"$davinterface\"}[$interval])) by (le,instance,interface))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(appsuite_webdav_requests_seconds_bucket{pod=\"$pod\",interface=\"$davinterface\"}[$interval])) by (le,instance,interface))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(appsuite_webdav_requests_seconds_bucket{pod=\"$pod\",interface=\"$davinterface\"}[$interval])) by (le,instance,interface))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(appsuite_webdav_requests_seconds_bucket{pod=\"$pod\",interface=\"$davinterface\"}[$interval])) by (le,instance,interface))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(appsuite_webdav_requests_seconds_bucket{pod=\"$pod\",interface=\"$davinterface\"}[$interval])) by (le,instance,interface))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(appsuite_webdav_requests_seconds_bucket{pod=\"$pod\",interface=\"$davinterface\"}[$interval])) by (le,instance,interface))",
     "legendFormat": "p999"
    },
    {
     "expr": "sum(rate(appsuite_webdav_requests_seconds_sum{pod=\"$pod\",interface=\"$davinterface\"}[$interval]))/sum(rate(appsuite_webdav_requests_seconds_count{pod=\"$pod\",interface=\"$davinterface\"}[$interval]))",
     "legendFormat": "avg"
    },
    {
     "expr": "sum(appsuite_webdav_requests_seconds_max{pod=\"$pod\",interface=\"$davinterface\"})",
     "legendFormat": "max"
    }
   ]
  },
  { "title": "SOAP API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 126 } },
  {
   "title": "Requests (per-second)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 127 },
   "yaxes": [
    { "format": "cps", "label": "Counts/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(appsuite_soapapi_requests_seconds_count{pod=\"$pod\"}[$interval]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(rate(appsuite_soapapi_requests_seconds_count{status=~\"OK\",pod=\"$pod\"}[$interval]))",
     "legendFormat": "OK"
    },
    {
     "expr": "sum(rate(appsuite_soapapi_requests_seconds_count{status!~\"OK\",pod=\"$pod\"}[$interval]))",
     "legendFormat": "KO"
    }
   ]
  },
  {
   "title": "Response Time Percentiles",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 127 },
   "yaxes": [
    { "format": "s", "label": "Response Time" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(appsuite_soapapi_requests_seconds_bucket{pod=\"$pod\"}[$interval])) by (le,instance))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(appsuite_soapapi_requests_seconds_bucket{pod=\"$pod\"}[$interval])) by (le,instance))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(appsuite_soapapi_requests_seconds_bucket{pod=\"$pod\"}[$interval])) by (le,instance))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(appsuite_soapapi_requests_seconds_bucket{pod=\"$pod\"}[$interval])) by (le,instance))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(appsuite_soapapi_requests_seconds_bucket{pod=\"$pod\"}[$interval])) by (le,instance))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(appsuite_soapapi_requests_seconds_bucket{pod=\"$pod\"}[$interval])) by (le,instance))",
     "legendFormat": "p999"
    },
    {
     "expr": "sum(rate(appsuite_soapapi_requests_seconds_sum{pod=\"$pod\"}[$interval]))/sum(rate(appsuite_soapapi_requests_seconds_count{pod=\"$pod\"}[$interval]))",
     "legendFormat": "avg"
    },
    {
     "expr": "sum(appsuite_soapapi_requests_seconds_max{pod=\"$pod\"})",
     "legendFormat": "max"
    }
   ]
  },
  { "title": "IMAP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 135 } },
  {
   "title": "Failure Ratio",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 136 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum without (instance, status, host) (rate(appsuite_imap_commands_seconds_count{status!~\"OK\"}[1m])) / sum without (instance, status, host) (rate(appsuite_imap_commands_seconds_count[1m]))"
    }
   ]
  },
  {
   "title": "Requests (per-second)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 136 },
   "yaxes": [
    { "format": "reqps", "label": "Requests/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(appsuite_imap_commands_seconds_count{pod=\"$pod\"}[$interval]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(rate(appsuite_imap_commands_seconds_count{status=~\"OK\",pod=\"$pod\"}[$interval]))",
     "legendFormat": "OK"
    },
    {
     "expr": "sum(rate(appsuite_imap_commands_seconds_count{status!~\"OK\",pod=\"$pod\"}[$interval]))",
     "legendFormat": "KO"
    }
   ]
  },
  { "title": "CircuitBreaker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 144 } },
  {
   "title": "CLOSED",
   "type": "singlestat",
   "description": "Number of closed CircuitBreaker",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 145 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(appsuite_circuitbreaker_state{state=\"CLOSED\"})"
    }
   ]
  },
  {
   "title": "HALF_OPEN",
   "type": "singlestat",
   "description": "Number of half-open CircuitBreaker",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 145 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(appsuite_circuitbreaker_state{state=\"HALF_OPEN\"})"
    }
   ]
  },
  {
   "title": "OPEN",
   "type": "singlestat",
   "description": "Number of open CircuitBreaker",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 149 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(appsuite_circuitbreaker_state{state=\"OPEN\"})"
    }
   ]
  },
  {
   "title": "Denial Rate: $circuitbreaker_name",
   "type": "graph",
   "description": "The number of times an execution was denied because the circuit was open.",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 145 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(appsuite_circuitbreaker_denials_total{pod=\"$pod\", name=~\"$circuitbreaker_name\"}[$interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Open Rate: $circuitbreaker_name",
   "type": "graph",
   "description": "The number of times the circuit was opened.",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 145 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(appsuite_circuitbreaker_opens_total{pod=\"$pod\", name=~\"$circuitbreaker_name\"}[$interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "States",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 157 },
   "targets": [
    {
     "expr": "count(appsuite_circuitbreaker_state{pod=\"$pod\"} > 0) by (host, name, state)"
    }
   ]
  }
 ]
}