{
 "title": "JVM",
 "tags": [ "java" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1m,5m,1h,6h,1d" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_pod_info, namespace)"
   },
   {
    "name": "app",
    "label": "App",
    "query": "label_values(up{namespace=\"$namespace\"}, app)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(kube_pod_info{namespace=\"$namespace\", pod=~\".*$app.*\"}, pod)"
   },
   {
    "name": "mem_pools_heap",
    "label": "Memory Pools Heap",
    "query": "label_values(jvm_memory_used_bytes{pod=\"$pod\", area=\"heap\"}, id)"
   },
   {
    "name": "mem_pools_nonheap",
    "label": "Memory Pools Non-Heap",
    "query": "label_values(jvm_memory_used_bytes{pod=\"$pod\", area=\"nonheap\"}, id)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_uptime_seconds{pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "singlestat",
   "description": "Current thread count of a JVM.",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "jvm_threads_live_threads{pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Heap",
   "type": "graph",
   "description": "Used bytes of a given JVM memory area.",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{pod=\"$pod\", area=\"heap\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{pod=\"$pod\", area=\"heap\"})",
     "legendFormat": "Committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{pod=\"$pod\", area=\"heap\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Non-Heap",
   "type": "graph",
   "description": "Used bytes of a given JVM memory area.",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{pod=\"$pod\", area=\"nonheap\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{pod=\"$pod\", area=\"nonheap\"})",
     "legendFormat": "Committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{pod=\"$pod\", area=\"nonheap\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Classes loaded",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "jvm_classes_loaded_classes{pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Classes unloaded",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "jvm_classes_unloaded_classes_total{pod=\"$pod\"}"
    }
   ]
  },
  { "title": "Memory Pools (Heap)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "$mem_pools_heap",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "repeat": "mem_pools_heap",
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{pod=\"$pod\", area=\"heap\", id=~\"$mem_pools_heap\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{pod=\"$pod\", area=\"heap\", id=~\"$mem_pools_heap\"})",
     "legendFormat": "Committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{pod=\"$pod\", area=\"heap\", id=~\"$mem_pools_heap\"})",
     "legendFormat": "Max"
    }
   ]
  },
  { "title": "Memory Pools (Non-Heap)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "$mem_pools_nonheap",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "repeat": "mem_pools_nonheap",
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{pod=\"$pod\", area=\"nonheap\", id=~\"$mem_pools_nonheap\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{pod=\"$pod\", area=\"nonheap\", id=~\"$mem_pools_nonheap\"})",
     "legendFormat": "Committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{pod=\"$pod\", area=\"nonheap\", id=~\"$mem_pools_nonheap\"})",
     "legendFormat": "Max"
    }
   ]
  },
  { "title": "Garbage Collector", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "GC duration",
   "type": "graph",
   "description": "Used bytes of a given JVM memory area.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{pod=\"$pod\"}[$interval])/rate(jvm_gc_collection_seconds_count{pod=\"$pod\"}[$interval])",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "Collection",
   "type": "graph",
   "description": "Used bytes of a given JVM memory area.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_count{pod=\"$pod\"}[$interval])",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  { "title": "Thread", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_live_threads{pod=\"$pod\"}",
     "legendFormat": "Live"
    },
    {
     "expr": "jvm_threads_daemon_threads{pod=\"$pod\"}",
     "legendFormat": "Daemon"
    },
    {
     "expr": "jvm_threads_peak_threads{pod=\"$pod\"}",
     "legendFormat": "Peak"
    }
   ]
  },
  {
   "title": "Thread States",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_states_threads{pod=\"$pod\"}",
     "legendFormat": "{{state}}"
    }
   ]
  }
 ]
}