{{- define "core-mw.typeSpecific.properties-lean-configmap.options" -}}
usedKeys:
  - configuration
{{- end -}}

{{- define "core-mw.typeSpecific.properties-lean-configmap.template" -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .ResourceName }}
  namespace: {{ .Context.Release.Namespace }}
  labels:
    {{- include "ox-common.labels.standard" .Context | nindent 4 }}
data:
{{ tpl (.Context.Files.Glob "config/logback.xml").AsConfig (dict "Values" .Values "Template" .Context.Template) | indent 2 }}
  languages.properties: |-
{{ tpl (.Context.Files.Get "config/languages/languages.properties") .Context | indent 4 }}
  properties-lean-config.properties: |-
{{ printf "### This file was generated by Helm (%s)" .Context.Chart.Name | indent 4 }}
{{ range $path, $_ := (.Context.Files.Glob "config/*.properties") }}
{{ printf "# %s" $path | indent 4 }}
{{ tpl ($.Context.Files.Get $path) $.Context | indent 4 }}
{{- end }}
{{- end -}}
